### PR TITLE
Fix example `npm start` and  migrate from easyrtc@1 to open-easyrtc@2

### PR DESCRIPTION
**Pull request by hthetiot**
Again this fix more than  487 vulnerabilities  and improve easyrtc WebRTC support.
Full EasyRTC to OpenEasyRTC ChangeLogs: open-easyrtc/open-easyrtc#6

### CODE REVIEW

**Comment by hthetiot** [comment]
@haydenjameslee this fix the basic errors of missing socket.io, missing easyrtc loading in example, missing dist staticServe. 

This make this naf-easyrtc-adapter works where before it was not functional.

**Comment by hthetiot** [comment]
after this fixes the module works properly

> npm i
> npm start

Screen Shot 2020-02-08 at 3 40 27 PM

**Comment by hthetiot** [comment]
Cc @haydenjameslee please consider my PR to fix this project issues.
Thank you.

**Comment by haydenjameslee** [comment]
@hthetiot What do you think about making a new repo for open-easyrtc, so that people who require the old easyrtc for any reason can use this one, and people wanting open can use this change? We could put big bold letters on the top of the easyrtc repo saying its deprecated and not recommended anymore. This makes sense to me because they are different libraries (even though they have the same API).

**Comment by hthetiot** [comment]
@haydenjameslee ok but why not simply merging this ? It take one click no ?

**Comment by hthetiot** [comment]
Note: the old easyRTC is dead Priologic removed it from GitHub, also old easyRTC is full of security issues. Letting user use the old easyRTC is putting user at risk, also this PR fix more than easyRTC it fix basically this repository to work out of the box.

**Comment by hthetiot** [comment]
Conclusion there only one easyRTC now it's Open-EasyRTC therefore you should merge this PR and we can just move on.

**Comment by hthetiot** [comment]
This is a shame.... Why not fixing all the issues that make that repository works and update to open-easyrtc at the same time....

**Comment by hthetiot** [comment]
Up.

**Comment by kylebakerio** [comment]
So, just fixing this doesn't give any testable demo, because the example in this repo uses aframe 0.7 and NAF 0.3 (on top of that, some custom iteration where hayden seems to have first tested the idea of 'NAF.adapter.register()', which later became standard). So, combing the changes in this pull request, with updates in the basic audio in the latest NAF, and bumping up versions of things, I came up with this glitch: https://glitch.com/edit/#!/naf-071-openeasyrtc?path=README.md%3A31%3A0

Sadly, the result is still not functional. Worth noting, however, is that I'm on a mobile hotspot, which requires a more robust webrtc implementation--this may now work, but perhaps I can't tell. At the time, I can't test on any other networks.

Locally, it seems fine. I open two tabs, I get feedback. Logs show connections seem to be going through, supposedly.

However, when I have someone at a distance log in, it fails to get any audio going through. 

This is also true if I revert to 0.6.1 in the demo, basically, though things can be worse.

When I try to use the original easyrtc demo glitch out there, [here](https://glitch.com/edit/#!/networked-aframe-audio?path=server.js%3A14%3A0), it gives me very weird results and frequent glitches where only some players can see others players some of the time.

I can't seem to find any permutation of NAF that ever worked consistently (with webrtc audio with my current setup behind a mobile hotspot), and am starting to suspect it has always been broken, at least for my scenario. I'm not sure where to look, but I'm starting to think the adapter isn't the right place, it's NAF itself. Makes it tempting to just use NAF for networked objects and orientation, and just try to do webrtc audio/video from scratch using `peer.js` for example. If the problem is just that NAT punchthrough needs better implementation, however, then I'd run into that when rolling my own as well, and if that is the case, I will probably just look to follow through on the open-easyrtc implementation further.

**Comment by kylebakerio** [comment]
I've gone ahead and made a fork with my version here: https://github.com/kylebakerio/naf-easyrtc-adapter/blob/master/README.md

**Comment by hthetiot** [comment]
@kylebakerio Thank you I merged your PR into open-easyrtc branch of open-easyrtc naf-easyrtc-adapter fork.
Your changes are now included in this PR.

**Comment by hthetiot** [comment]
Please @haydenjameslee make me and @kylebakerio maintainers on this repository so we can help your project continue to be secure and works with easyrtc.

**Comment by vincentfretin** [comment]
The easyrtc adapter moved again to the networked-aframe repository. I'm closing all issues in this repository.

**Pull request closed without merging**
